@url = http://localhost:8000
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTWFyaWx5bmUuTGVta2U3NkBnbWFpbC5jb20iLCJpYXQiOjE3NDkxNDM0MzUsImV4cCI6MTc0OTE0NDMzNX0.2oOQpXWOcAj5Nvy2zZ_tKgZc_KqJgjmj_aKvB3KFeKs
@RefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTWFyaWx5bmUuTGVta2U3NkBnbWFpbC5jb20iLCJpYXQiOjE3NDkxNDM0MzUsImV4cCI6MTc0OTc0ODIzNX0.O_cqYPqrJS95BY_XnR1cziaqxXXNnI_j5U0zxWu0QlI

POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "Marilyne.Lemke76@gmail.com",
  "password": "password"
}

###
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "password": "password",
  "role": "admin"
}

###
# Users
GET {{url}}/users
Authorization: Bearer {{AccessToken}}
###
GET {{url}}/auth/refresh?id=1
Authorization: Bearer {{RefreshToken}}

###
GET {{url}}/auth/signout/1

###
POST {{url}}/seed



###
DELETE {{url}}/users/2
Authorization: Bearer {{AccessToken}}

###
# Products
GET {{url}}/products
Authorization: Bearer {{AccessToken}}


GET {{url}}/warehouses
Authorization: Bearer {{AccessToken}}


GET {{url}}/orders
Authorization: Bearer {{AccessToken}}