@url = http://localhost:8000/api
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTWFyaWx5bmUuTGVta2U3NkBnbWFpbC5jb20iLCJpYXQiOjE3NDk1NTcyMzEsImV4cCI6MTc0OTU1ODEzMX0.ojz8g2SdppdW-uoW78RXbr45Wwv9qPprOlYIgFGDilw
@RefreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiTWFyaWx5bmUuTGVta2U3NkBnbWFpbC5jb20iLCJpYXQiOjE3NDk1NTcyMzEsImV4cCI6MTc1MDE2MjAzMX0.YWoGO66cUCziV6FHs_eG_XgTQbjcYA-MsHCZTA6bHnc

POST {{url}}/auth/signin
Content-Type: application/json

{
  "email": "Marilyne.Lemke76@gmail.com",
  "password": "password"
}

###
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@example.com",
  "password": "password",
  "role": "admin"
}

###
# Users
GET {{url}}/users?search=Hiram
Authorization: Bearer {{AccessToken}}

###
GET {{url}}/auth/refresh?id=1
Authorization: Bearer {{RefreshToken}}

###
GET {{url}}/auth/signout/1

###
POST {{url}}/seed



###
DELETE {{url}}/users/2
Authorization: Bearer {{AccessToken}}

###
# Products
GET {{url}}/products
Authorization: Bearer {{AccessToken}}


GET {{url}}/warehouses
Authorization: Bearer {{AccessToken}}


GET {{url}}/orders
Authorization: Bearer {{AccessToken}}