version: '3.8'

services:
  InventoryManagement:
    image: postgres:15-alpine
    container_name: InventoryManagement
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LxfwP7haEW0K
      POSTGRES_DB: InventoryManagement
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    networks:
      - app-networks
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:8.0-alpine
    container_name: redis-cache
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-password}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-password}", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-app
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: InventoryManagement
      NEON_DATABASE_URL: ${NEON_DATABASE_URL:-postgresql://restuarantdb_owner:LxfwP7haEW0K@ep-weathered-frost-a5oh2con-pooler.us-east-2.aws.neon.tech/InventoryManagement?sslmode=require}
      DB_SYNC: ${DB_SYNC:-true}
      DB_LOGGING: ${DB_LOGGING:-false}
      REDIS_HOST: ${REDIS_HOST-localhost}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_URL: redis://:${REDIS_PASSWORD:-password}@${REDIS_HOST:-localhost}:${REDIS_PORT:-6379}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET:-your_access_token}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET:-your_refresh_token}
      ACCESS_TOKEN_EXPIRES_IN: ${ACCESS_TOKEN_EXPIRES_IN:-15m}
      REFRESH_TOKEN_EXPIRES_IN: ${REFRESH_TOKEN_EXPIRES_IN:-7d}
      RESET_TOKEN_SECRET: ${RESET_TOKEN_SECRET:-your_reset_token_secret}
      RESET_TOKEN_EXPIRES_IN: ${RESET_TOKEN_EXPIRES_IN:-1h}
      SMTP_USER: ${SMTP_USER:-victornjeru49@gmail.com}
      SMTP_PASS: ${SMTP_PASS:-stno mlwg xtcz wfgq}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      THROTTLE_TTL: ${THROTTLE_TTL:-90000}
      THROTTLE_LIMIT: ${THROTTLE_LIMIT:-100}
    depends_on:
      InventoryManagement:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-networks
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
    name: inventory-app-pgdata
    driver: local
  redis-data:
    name: inventory-InventoryManagement-redis-data
    driver: local

networks:
  app-networks:
    driver: bridge
