version: '3.8'

services:
  Products:
    image: postgres:15-alpine
    container_name: Products
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 14690
      POSTGRES_DB: Products
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Products"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - app-network

volumes:
  pgdata:
    name: Products-db-data
    driver: local

networks:
  app-network:
    driver: bridge